### PR TITLE
modified splash.dart file

### PR DESCRIPTION
**Pull request by DaNnyKg07**
Changed the color of icons and background color of the scaffold

### CODE REVIEW

**Comment by therealansh** [comment]
Please add a ss to the changes and other PRs

**Comment by DaNnyKg07** [comment]
<table>
  <tr>
    <td>Before</td>
     <td>Now</td>
  </tr>
  <tr>
    <td> </td>
    <td></td>
    </tr>
 </table>

**Comment by therealansh** [comment]
Pull the changes and Rebase the PRs with the master and then push the changes in your branch

**Comment by therealansh** [comment]
Remove the merge conflicts accordingly

**Pull request closed without merging**
