### PR TITLE
APP ICON ADDED

### PR DESCRIPTION
**Pull request by vaibhavpromax**

### CODE REVIEW

**Comment by therealansh** [comment]
Hey @vaibhavpromax Thanks for the PR. Can you attach some ss and to which devices you added this app logo?

**Comment by vaibhavpromax** [comment]
> Hey @vaibhavpromax Thanks for the PR. Can you attach some ss and to which devices you added this app logo?

Screenshot_1619705464
Android and ios

**Comment by vaibhavpromax** [comment]
Screenshot_1619893931

**Comment by therealansh** [comment]
LGTM thanks for the PR!

**Pull request merged**
